-- DROP DATABASE
-- DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
-- CREATE DATABASE ecommerce_db;


CREATE TABLE Category (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    category_name VARCHAR(30) NOT NULL
);

CREATE TABLE Tag (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    tag_name VARCHAR(30) NOT NULL
);

CREATE TABLE Product (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  product_name VARCHAR(30) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  stock INT DEFAULT 10 NOT NULL,
  category_id INT NOT NULL,
  FOREIGN KEY (category_id) REFERENCES Category(id)
);



CREATE TABLE Product_Tag (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_id INT, 
    tag_id INT,
    FOREIGN KEY (product_id) REFERENCES Product(id),
    FOREIGN KEY (tag_id) REFERENCES Tag(id)
);

